name: Frontend CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Install & Run Frontend Tests
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Jest tests
        working-directory: ./frontend
        run: |
          npm install --no-save jest-junit
          npm test -- --watchAll=false --coverage --reporters=default --reporters=jest-junit

      - name: Upload Jest test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: frontend/test-results.xml

      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage
          path: frontend/coverage
