name: Frontend CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Install & Run Frontend Tests
    runs-on: ubuntu-latest
    env:
      CI: true                   # Ensure Create React App / Jest runs in CI mode

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'           # Cache ~/.npm to speed up installs

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci             # `npm ci` is faster and more reliable in CI

      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

      - name: Upload Jest test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: frontend/test-results.xml
