name: Frontend CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Install & Run Frontend Tests in Docker
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run frontend tests inside Docker
        run: |
          docker build -t frontend-test ./frontend
          docker run --rm frontend-test npm test -- --watchAll=false
